### ISSUE TITLE
Colors differ from screenshots

### ISSUE THREAD

**Issue by cer-0** [Cardoso1994/doom-gruvbox-material-theme#2]
Hey!, just installed Emacs and vanilla Doom, after enabling the theme the colors do no seem to match the screenshots.

Emacs version: `28.2`
Doom version: 
```
Doom core     v3.0.0-pre       grafted, HEAD -> master, origin/master, origin/HEAD 042fe0c 2023-04-12 15:09:23 -0400
Doom modules  v23.03.0-pre     grafted, HEAD -> master, origin/master, origin/HEAD 042fe0c 2023-04-12 15:09:23 -0400
```
Screenshot:
![image](https://user-images.githubusercontent.com/49457264/233232582-72f0eddb-b733-425f-acf2-3b372a2d481f.png)

I replicated this on two setups now, let me know if I missed something. Also, thank you for porting this theme. (:

**Comment by Cardoso1994** [comment]
Hi!

Sorry, my bad. As per the last commit, I changed some colors to reduce the ammount of red in the theme; now it is more greenish.

I do need to update the screenshots, though.

**Comment by cer-0** [comment]
Oh! I see, thank you, I'll close this issue then. (:
